<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>10</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>EPrimeReadouts.Core</RootNamespace>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(RimSharedRoot)\Common\**\*.cs" LinkBase="Shared" />
  </ItemGroup>
</Project>
